### PR TITLE
allow for no_std builds

### PR DESCRIPTION
**Pull request by whalelephant**
- added features to toml
- use alloc and core when no_std
- impl error only for std

### CODE REVIEW

**Comment by vmx** [comment]
@OrKoN is there a chance to get this merged? I'd like to prevent forks where possible.

**Comment by OrKoN** [comment]
@dignifiedquire @maciejhirsz Could you please help review this PR?

**Review by maciejhirsz — APPROVED** [review]
Looks good to me, could use CI to check it builds in both settings.

**Comment by vmx** [comment]
Thanks for merging and releasing this so quickly!

**Pull request merged**
