### PR TITLE
Add simple benchmarks

### PR DESCRIPTION
**Pull request by dignifiedquire**
These can be run with `cargo bench`.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
cc @maciejhirsz

**Comment by OrKoN** [comment]
FYI I have another related project here: https://github.com/OrKoN/base-x-native this are node bindings to this library using the Neon project. There is a simple benchmark from the original project too.

**Comment by OrKoN** [comment]
I still have to adapt it to the latest changes.

**Comment by maciejhirsz** [comment]
I tend to bench with the built in nightly bencher, but this looks good. Going to be interesting to see a custom Alphabet struct vs generic ASCII vs generic Unicode.

@OrKoN do you have benchmarks for base-x-native vs the plain JS implementation? Neon does introduce some overhead when doing a call to Rust (compared to raw C++ compiled with `node-gyp`, which is as low level as it can get).

**Comment by OrKoN** [comment]
@maciejhirsz the original project (plain JS implementation) has benchmarks too https://github.com/cryptocoinjs/base-x/tree/master/benchmark The benchmarks in base-x-native are basically the same - just implementation is via Rust/Neon because the interface does not change.

**Comment by OrKoN** [comment]
selection_124

this is the current results with the new version.

**Comment by maciejhirsz** [comment]
Interesting. Try again after #8 is merged.

When I was running benches in void, Rust was 50% ahead of JS when encoding and roughly 10 times faster when decoding. Decoding works on much smaller time values though, so there the overhead of Neon will be more significant.

If you are into that, here is a good run on it: https://github.com/wtfil/rust-in-node

If you want to maximize performance, doing Rust bindings to C++ and making an addon out of that is probably your best bet.

**Pull request merged**
